version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/build/:/etc/nginx/frontend/
        ports:
            - 9000:80

        links: 
            - backend


    backend:
        build: backend/
        links:
            - db
        environment:
            frontendurl: localhost/
            PGHOST: db
            PGUSER: postgres
            PGDATABASE: ntnuib
            PGPASSWORD: pgspass 
        ports:
            - 8000:8000
        depends_on:
            - db

    db: 
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: pgspass
        volumes:
            - db-data:/var/lib/postgresql/data

        
volumes:
    db-data: